import { useEffect, useRef, type FormEvent } from 'react'
import type { Lote } from '@features/lotes/api/lotes'
import type { TipoAlimento } from '@features/consumos-diarios/api/tipos-alimento'
import type { FormularioConsumo as DatosConsumo } from '../model/consumoDiario'

type Props = { form: DatosConsumo; lotes: Lote[]; tiposAlimento: TipoAlimento[]; modoEdicion: boolean; guardando: boolean; error: string; onCambiar: <K extends keyof DatosConsumo>(campo: K, valor: DatosConsumo[K]) => void; onGuardar: (evento: FormEvent<HTMLFormElement>) => void; onCerrar: () => void }

function FormularioConsumo({ form, lotes, tiposAlimento, modoEdicion, guardando, error, onCambiar, onGuardar, onCerrar }: Props) {
  const loteRef = useRef<HTMLSelectElement>(null)
  useEffect(() => { loteRef.current?.focus(); const escape = (e: KeyboardEvent) => { if (e.key === 'Escape' && !guardando) onCerrar() }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, [guardando, onCerrar])
  return <div className="cd-modal-fondo" onMouseDown={onCerrar}><section className="cd-modal" role="dialog" aria-modal="true" aria-labelledby="cd-modal-titulo" onMouseDown={(e) => e.stopPropagation()}><header><h2 id="cd-modal-titulo">{modoEdicion ? 'Editar consumo' : 'Registrar consumo'}</h2><p>Registra alimento, agua o ambos.</p></header><form onSubmit={onGuardar}><label><span>Lote *</span><select ref={loteRef} value={form.lote_id} onChange={(e) => onCambiar('lote_id', e.target.value)} required><option value="">Selecciona un lote</option>{lotes.map((lote) => <option key={lote.id} value={lote.id}>{lote.codigo} · {lote.galpon.nombre}</option>)}</select></label><div className="cd-dos"><label><span>Fecha *</span><input type="date" value={form.fecha} onChange={(e) => onCambiar('fecha', e.target.value)} required /></label><label><span>Tipo de alimento</span><select value={form.tipo_alimento_id} onChange={(e) => onCambiar('tipo_alimento_id', e.target.value)}><option value="">No se registró alimento</option>{tiposAlimento.map((tipo) => <option key={tipo.id} value={tipo.id}>{tipo.nombre}{tipo.etapa ? ` · ${tipo.etapa}` : ''}</option>)}</select></label></div><div className="cd-dos"><label><span>Alimento consumido (kg)</span><input type="number" inputMode="decimal" min="0" step="0.001" value={form.alimento_kg} onChange={(e) => onCambiar('alimento_kg', e.target.value)} /></label><label><span>Agua consumida (litros)</span><input type="number" inputMode="decimal" min="0" step="0.001" value={form.agua_litros} onChange={(e) => onCambiar('agua_litros', e.target.value)} /></label></div>{error && <p className="cd-error" role="alert">{error}</p>}<footer><button type="button" onClick={onCerrar} disabled={guardando}>Cancelar</button><button className="cd-primario" type="submit" disabled={guardando}>{guardando ? 'Guardando…' : modoEdicion ? 'Guardar cambios' : 'Registrar consumo'}</button></footer></form></section></div>
}
export default FormularioConsumo
