// Punto único de importación de la capa de API.
// Uso: import { login, listarGranjas, calcularIndicadores } from '@shared/api'

export { api } from './client'
export * from './tokens'
export * from './auth'
export * from './usuarios'
export * from './sensores'
export * from './mediciones'
export * from './granjas'
export * from './galpones'
export * from './lotes'
export * from './proveedores'
export * from './insumos'
export * from './tipos-alimento'
export * from './pesajes'
export * from './consumos-diarios'
export * from './registros-mortalidad'
export * from './eventos-sanitarios'
export * from './registros-plagas'
export * from './dispositivos'
export * from './umbrales'
export * from './auditoria'
export * from './indicadores'
export * from './curvas-objetivo'
export * from './alertas'
export * from './alertas-canales'
export * from './politicas-alertas'
export * from './evidencias-alertas'
export * from './accionamientos'
export * from './equipos'
export * from './ordenes-compra'
export * from './movimientos-financieros'
export * from './cotizaciones'
export * from './prospectos'
export * from './copiloto'
export * from './predicciones'
export * from './recomendaciones'
export * from './clima'
export * from './solicitudes-pqrs'
export * from './interacciones-chatbot'
export * from './notificaciones'
export type * from './types'
